from selenium import webdriver
import time
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("https://demo.automationtesting.in/Register.html")
time.sleep(3)
first_name = driver.find_element_by_css_selector("input[placeholder='First Name']")
first_name.send_keys("Test")
time.sleep(3)
last_name = driver.find_element_by_css_selector("input[placeholder='Last Name']")
last_name.send_keys("Test")
time.sleep(3)
email = driver.find_element_by_css_selector("input[ng-model='EmailAdress']")
email.send_keys("test@bk.ru")
time.sleep(3)
phone = driver.find_element_by_css_selector("input[ng-model='Phone']")
phone.send_keys("1086594329")
time.sleep(3)
gender_option = driver.find_element_by_css_selector("input[value='FeMale']").click()
from selenium.webdriver.support.select import Select
country_element = driver.find_element_by_id("country")
select = Select(country_element)
select.select_by_value("Hong Kong")
time.sleep(3)
year_element = driver.find_element_by_id("yearbox")
select = Select(year_element)
select.select_by_value("1987")
time.sleep(3)
month_element = driver.find_element_by_css_selector("select[placeholder='Month']")
select = Select(month_element)
select.select_by_value("January")
time.sleep(3)
day_element = driver.find_element_by_id("daybox")
select = Select(day_element)
select.select_by_value("29")
time.sleep(3)
password = driver.find_element_by_css_selector("input[ng-model='Password']")
password.send_keys("Test123")
time.sleep(3)
confirm_password = driver.find_element_by_css_selector("input[ng-model='CPassword']")
confirm_password.send_keys("Test123")
time.sleep(3)
photo = ('C:\cosmic_dream_4k.jpg')
upload = driver.find_element_by_id("imagesrc")
upload.send_keys(photo)
time.sleep(3)
driver.execute_script("window.scrollBy(0, 300);")
time.sleep(3)
driver.find_element_by_id("submitbtn").click()
time.sleep(3)
current_page = driver.current_url
expected_adress = "http://demo.automationtesting.in/WebTable.html"
if current_page == expected_adress:
    print("Адрес страницы совпадает")
else:
    print("Адрес страницы не совпадает, фактический:", current_page)
    print("Ожидаемый адрес страницы:", expected_adress)
time.sleep(3)
driver.quit()