from selenium import webdriver
import time
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("https://demo.us.espocrm.com/")
time.sleep(3)
from selenium.webdriver.support.select import Select
language_element = driver.find_element_by_tag_name("select#field-language.form-control")
select = Select(language_element)
select.select_by_value("en_US")
driver.find_element_by_id("btn-login").click()
time.sleep(3)
#driver.find_element_by_link_text("Activities").click() #клик не срабатывает, область некликабельна
driver.find_element_by_link_text("More").click()
time.sleep(3)
driver.find_element_by_link_text("Tasks").click()
time.sleep(3)
driver.find_element_by_css_selector("button.btn.dropdown-toggle.filters-button.btn-default").click()
time.sleep(3)
driver.find_element_by_css_selector("li.checkbox:nth-child(11)").click()
time.sleep(3)
driver.find_element_by_css_selector(".select-all.form-checkbox.form-checkbox-small").click()
time.sleep(3)
driver.find_element_by_css_selector("button.actions-button[data-toggle='dropdown']").click()
time.sleep(3)
driver.find_element_by_link_text("Mass Update").click()
time.sleep(3)
update_btn = driver.find_element_by_css_selector(".btn.btn-danger.btn-xs-wide")
update_btn_disabled = update_btn.get_attribute("disabled")
if update_btn_disabled is None:
    print("Кнопка Update доступна для выбора")
else:
    print("Кнопка Update недоступна для выбора")
driver.find_element_by_css_selector(".close").click()
time.sleep(3)
driver.find_element_by_css_selector(".btn.btn-default.btn-xs-wide.main-header-manu-action.action.radius-left.radius-right").click()
time.sleep(5)
name = driver.find_element_by_xpath('//input[@data-name="name"]')
name.send_keys("Test")
time.sleep(3)
status_element = driver.find_element_by_css_selector(".col-sm-6:nth-child(1) select")
selected_value = status_element.get_attribute("value")
if selected_value == "Not Started":
    print("Значение 'Not Started' выбрано в 'Status'")
else:
    print("Значение в 'Status' не равно 'Not Started'")
driver.find_element_by_css_selector(".btn-xs-wide:nth-child(1)").click()
time.sleep(3)
driver.find_element_by_css_selector(".breadcrumb-item .action").click()
time.sleep(3)
driver.find_element_by_css_selector(".list-row:nth-child(1) .record-checkbox.form-checkbox.form-checkbox-small").click()
time.sleep(3)
driver.find_element_by_css_selector("button.actions-button[data-toggle='dropdown']").click()
time.sleep(3)
driver.find_element_by_link_text("Remove").click()
time.sleep(3)
driver.quit()