import time
from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("https://opensource-demo.orangehrmlive.com/")
time.sleep(3)
login = driver.find_element_by_name("username")
login.send_keys("Admin")
password = driver.find_element_by_name("password")
password.send_keys("admin123")
login_btn = driver.find_element_by_css_selector(".oxd-button")
login_btn.click()
time.sleep(3)
pim_btn = driver.find_element_by_link_text("PIM")
pim_btn.click()
time.sleep(3)
employee_id = driver.find_element_by_css_selector("div:nth-child(2) > input")
employee_id.send_keys("*") # вместо звёздочки ввод значения id (получившегося в предыдущем тесте)
search_btn = driver.find_element_by_css_selector(".oxd-button.oxd-button--medium.oxd-button--secondary.orangehrm-left-space")
search_btn.click()
time.sleep(3)
trash_btn = driver.find_element_by_css_selector(".oxd-icon.bi-trash")
trash_btn.click()
time.sleep(3)
yes_delete_btn = driver.find_element_by_css_selector(".oxd-button--medium.oxd-button--label-danger")
yes_delete_btn.click()
time.sleep(6)
driver.quit()