import time
from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("https://opensource-demo.orangehrmlive.com/")
time.sleep(3)
login = driver.find_element_by_name("username")
login.send_keys("Admin")
password = driver.find_element_by_name("password")
password.send_keys("admin123")
login_btn = driver.find_element_by_css_selector(".oxd-button")
login_btn.click()
time.sleep(3)
pim_btn = driver.find_element_by_link_text("PIM")
pim_btn.click()
time.sleep(3)
add_employee_tab = driver.find_element_by_link_text("Add Employee")
add_employee_tab.click()
time.sleep(3)
first_name = driver.find_element_by_name("firstName")
first_name.send_keys("Ivan")
last_name = driver.find_element_by_name("lastName")
last_name.send_keys("Ivanov")
employee_id = driver.find_element_by_css_selector(".oxd-grid-2 .oxd-input")
employee_id.send_keys("II")
time.sleep(3)
save_btn = driver.find_element_by_css_selector(".oxd-button--secondary[data-v-10d463b7]")
save_btn.click()
time.sleep(6)
driver.quit()