from selenium import webdriver
import time
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("https://www.saucedemo.com/")
time.sleep(3)
username_field = driver.find_element_by_id("user-name")
username_field.send_keys("standard_user")
password_field = driver.find_element_by_id("password")
password_field.send_keys("secret_sauce")
login_btn = driver.find_element_by_id("login-button")
login_btn.click()
time.sleep(3)
backpack = driver.find_element_by_id("add-to-cart-sauce-labs-backpack")
backpack.click()
time.sleep(3)
bike_light = driver.find_element_by_id("add-to-cart-sauce-labs-bike-light")
bike_light.click()
time.sleep(3)
fleece_jacket = driver.find_element_by_id("add-to-cart-sauce-labs-fleece-jacket")
fleece_jacket.click()
time.sleep(3)
cart = driver.find_element_by_class_name("shopping_cart_link")
cart.click()
time.sleep(3)
items_count = driver.find_elements_by_css_selector(".cart_item")
if len(items_count) == 3:
    print("В корзине 3 товара")
else:
    print("Ошибка. Количество товаров в корзине: " + str(len(items_count)))
time.sleep(3)
driver.quit()